## Arrays
Both vectors and matrices are `NumPy` arrays. Each array in `NumPy` has a dimension. Vectors are one-dimensional arrays while matrices are two-dimensional arrays.


In [2]:
import numpy as np
x = np.array([1, 2, 3])
M = np.array([[1, 2], [3, 4], [5, 6]])

print('x has shape', x.shape)
print('M has shape', M.shape)

print('x is an array of dimension', x.ndim)
print('M is an array of dimension', M.ndim)

x has shape (3,)
M has shape (3, 2)
x is an array of dimension 1
M is an array of dimension 2


## Reshaping

Arrays can be reshaped. We will start with an example. Let us start with a matrix

In [3]:
M = np.array([[1, 2, 3], [4, 5, 6]])
x = M.reshape(6)
x

array([1, 2, 3, 4, 5, 6])

In [4]:
x = np.array([1, 2, 3, 4, 5, 6])
M = x.reshape((3, 2))
M

array([[1, 2],
       [3, 4],
       [5, 6]])

## Matrix-vector addition (broadcasting)

In many ML models, we would have to add a vector to each row or column of a matrix. For example, consider the following case for row-wise addition:

In [5]:
M = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b = np.array([1, 1, 1, 1])
print('Shape of M:', M.shape)
print('Shape of b:', b.shape)

M + b

Shape of M: (2, 4)
Shape of b: (4,)


array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

## Column-wise addition 
 Same concept does not work for column wise additon , some fix has to be done to make it work

In [7]:
M = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b = np.array([1, 2])
print('Shape of M:', M.shape)
print('Shape of b:', b.shape)
#print(M + b) this will cause an error saying the dimensions of b are not compatible with M
# operands could not be broadcast together with shapes (2,4) (2,) 


Shape of M: (2, 4)
Shape of b: (2,)


In [8]:
M = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
b = np.array([1, 2])
print('Shape of M:', M.shape)
print('Shape of b before adding dimension:', b.shape)
b = np.expand_dims(b, 1)
print('Shape of b after adding dimension:', b.shape)

M + b

Shape of M: (2, 4)
Shape of b before adding dimension: (2,)
Shape of b after adding dimension: (2, 1)


array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10]])

## Stacking arrays

Sometimes, we would want to stack arrays. Consider the two matrices:

In [10]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = np.concatenate((A, B), axis = 0)
D= np.concatenate((A, B), axis = 1)
print(C.shape)
print(C)
print(D.shape)
print(D)

(4, 2)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
(2, 4)
[[1 2 5 6]
 [3 4 7 8]]


## Sum, Mean and Variance

Sometimes we may wish to compute the sum of a particular slice of an array. For example, consider the matrix:

In [14]:
A = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
rsum = A.sum(axis = 1)
csum = A.sum(axis = 0)

print('Sum of the rows:', rsum)
print('Sum of the columns:', csum)

rvar = A.var(axis = 1)
cvar = A.var(axis = 0)
print('Variance of the rows:', rvar)
print('Variance of the columns:', cvar)

rmean = A.mean(axis = 1)
cmean = A.mean(axis = 0)
print('Mean of the rows:', rmean)
print('Mean of the columns:', cmean)


Sum of the rows: [10 26]
Sum of the columns: [ 6  8 10 12]
Variance of the rows: [1.25 1.25]
Variance of the columns: [4. 4. 4. 4.]
Mean of the rows: [2.5 6.5]
Mean of the columns: [3. 4. 5. 6.]
