# Vectors


 Operations
- First we shall import NumPy package
- Then use it to define a vector as np array

In [23]:
#Suppose we have a vector v1 = [1, 2, 3, 4, 5]
#We can use the numpy.array function to create a numpy array from this vector:
import numpy as np
v1 = np.array([1, 2, 3, 4, 5])
print(v1)
print(type(v1))

[1 2 3 4 5]
<class 'numpy.ndarray'>


### Now let's define another vector using array and try to implement various vector operations using np :


- Addition

In [24]:
v2 = np.array([5,6,9,8,7])
v3 = v2 + v1
print(v3)

[ 6  8 12 12 12]


- Elementwise multiplication

In [25]:
v4= v2*v1
print(v4)

[ 5 12 27 32 35]


- Scaling

In [26]:
v5 = 2*v4
print(v5)

[10 24 54 64 70]


- Elementwise function of vectors


In [27]:
x = np.array([1,5,9,6,7])
y= x**3
# this apllies to all the elements in the array
print(y)

[  1 125 729 216 343]


In [28]:
x = np.array([1,2,4,8,16,32,64,128])
y = np.log2(x)
print(y)
l = np.array([1, np.e, np.e ** 2])
m = np.log(x)
print(m)

[0. 1. 2. 3. 4. 5. 6. 7.]
[0.         0.69314718 1.38629436 2.07944154 2.77258872 3.4657359
 4.15888308 4.85203026]


- Dot Product

The dot product between two vectors $\mathbf{x}$ and $\mathbf{y}$ is given as follows:

$$
z = \mathbf{x} \cdot \mathbf{y} = \sum \limits_{j = 1}^{m} x_j y_j
$$

In `NumPy`, this could be done as follows:

In [29]:
x = np.array([1, 2, 3, 4])
y = np.array([-41, -50, -60, -17])

z = np.dot(x, y)
z

-389

- Shape of a vector

All `NumPy` arrays have an attribute called `shape`. The shape is a tuple. For vectors (single-dimensional) the shape is of the form $(n, )$, where $n$ is the number of components in the vector.

In [30]:
x = np.array([10, 20, 30, 40])
print(x.shape)
x.shape[0] == len(x) #this holds true for any array


(4,)


True

- NumPy function of zeroes and ones

In [31]:
x = np.zeros(4)
print(x)
y= np.ones(4)
print(y)

[0. 0. 0. 0.]
[1. 1. 1. 1.]


# Matrices

- Matrix as a `NumPy` array

In [32]:
#Everything in `NumPy` is an array. A matrix is also an array. 
# The main difference is that a matrix is a two dimensional array. Let us create a simple matrix:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

- Adding two matrices

In [33]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = A + B
C

array([[ 6,  8],
       [10, 12]])

- Scaling matrices

In [34]:
#Scaling a matrix is nothing but element-wise multiplication:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
P = 3 * M
P


array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27]])

- Element-wise multiplication of two matrices

In [35]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

C = A * B
C

array([[ 5, 12],
       [21, 32]])

- Function of matrices (element-wise)

In [36]:
A = np.array([[-1, 2], [-3, -4]])
f_A = np.abs(A)   # np.abs returns the absolute value

print(f_A)
A = np.array([[1, 2], [3, 4]])
B = A ** 2

print(B)

[[1 2]
 [3 4]]
[[ 1  4]
 [ 9 16]]


- Transpose of a matrix

In [37]:
M = np.array([[1, 2, 3], [4, 5, 6]])
M_t = np.transpose(M)

print(M_t)
print('-----------')

#or

M = np.array([[1, 2, 3], [4, 5, 6]])
M_t = M.T

print(M_t)

[[1 4]
 [2 5]
 [3 6]]
-----------
[[1 4]
 [2 5]
 [3 6]]


- Product of two matrices

In [38]:
A = np.array([[1, 2, 3], [4, 5, 6]])
B = np.array([[6, 7], [8, 9], [10, 11]])

C = A @ B
C

array([[ 52,  58],
       [124, 139]])

- Product of a matrix and a vector

In [39]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
x = np.array([6, 7, 8])
C = A @ x

C

array([ 44, 107, 170])

- Shape of a matrix

In [40]:
M = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
M.shape

(4, 2)

- Matrix of zeros & Matrix of ones

In [41]:
M= np.zeros((2,2))
N= np.ones((2,2))
print(M)
print(N)

[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]]


- Identity Matrix

In [42]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])